"""Regenerates lib/motion/geo_data.dart (dotted-earth land mask).

pip install global-land-mask   # public-domain GLOBE-based land mask
python3 tool/generate_geo.py
"""
import math
from global_land_mask import globe


def rows(step, lat0, lat1, lon0, lon1, adjust=True):
    out, lat = [], lat0
    while lat <= lat1 + 1e-9:
        n, lon = [], lon0
        st = step / max(.25, math.cos(math.radians(lat))) if adjust else step
        while lon < lon1:
            if globe.is_land(lat, lon if lon <= 180 else lon - 360):
                n.append(round(lon, 1))
            lon += st
        if n:
            out.append((round(lat, 1), n))
        lat += step
    return out


def enc(rs):
    f = lambda x: (('%.1f' % x).rstrip('0').rstrip('.'))
    return ';'.join(f'{f(la)}:' + ','.join(f(x) for x in n) for la, n in rs)


def chunk(s, n=4000):
    return '\n'.join("    '" + s[i:i + n] + "'" for i in range(0, len(s), n))


W = enc(rows(1.8, -56, 78, -180, 180))
G = enc(rows(.45, 12, 32.5, 34, 60.5, adjust=False))
open('lib/motion/geo_data.dart', 'w').write(
    "// GENERATED by tool/generate_geo.py — do not edit by hand.\n\n"
    f"const String kWorldLand =\n{chunk(W)};\n\nconst String kGccLand =\n{chunk(G)};\n")
